### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by reckart** [vigna/DSI-Utilities#1]
According to the [POM](https://repo1.maven.org/maven2/it/unimi/dsi/dsiutils/2.3.3/dsiutils-2.3.3.pom) for dsiutils deployed to Maven Central, the code for the library should be available from here. Looks like that is not (so far) the case?

**Comment by vigna** [comment]
Nope. Presently it is just a placeholder. The source can be downloaded from http://dsiutils.di.unimi.it/

**Comment by reckart** [comment]
You might consider adding a link to the downloadable archive instead of the GitHub link - at least if you plan to continue not having a public source control management. Cf. https://issues.sonatype.org/browse/MVNCENTRAL-236
