### ISSUE TITLE
Remove compile dependency on logback-classic

### ISSUE THREAD

**Issue by reckart** [vigna/DSI-Utilities#2]
A library should not compile-depend on logging framework. DSI is coded against slf4j-api, but still has a compile dependency on logback-classic. This dependencies should be removed or switch to scope "test" if they are required for testing. Having these dependencies as compile-time dependencies requires downstream users to explicitly exclude them if they want to use another logging backend with slf4j.

**Comment by vigna** [comment]
Er... what is DL4J-core? This is the DSI utilities github discussion list.

**Comment by reckart** [comment]
Sorry for the confusion - I have corrected the issue text. The report remains valid.

DL4J is a library for deep learning. It has the same problem (compile-dependency on logback-classic). Actually, I stumbled across DSI by analyzing the transitive dependencies of DL4J-core.

**Comment by vigna** [comment]
OK, I marked the dependency with conf="runtime". That should work.

**Comment by reckart** [comment]
If you mark it as runtime, users who want to use another backend still will have to add an exclude. There should not be any dependency on the logging backend except "test". Not even "provided" makes sense in this case.

**Comment by vigna** [comment]
I see, you're right.
